### ISSUE TITLE
Address Collection : When Country Is Changed the Sates Don't get re-populated

### ISSUE THREAD

**Issue by sachingk** [orocommerce/orocommerce#42] opened 2017-07-06 06:25 UTC
I see there is a bug when using address collection. When the country is changed , the states have to re populate. However this is not happening.

I see this bug in ORO Commerce in the Admin Customer Management Screen - Both in Add Address via popup & Edit customer screen

That same issue is found in  my implementation on another screen.

I guess this bug is because is AddressCollectionTypeSubscriber missing from the Github Source code. But Documentation say I have to add that as a Event Listener to the form

**Comment by dnahrebecki** [comment] 2017-07-19 08:39
Hello @sachingk,

which version of application do you use? Also, please provide more detailed steps to reproduce.
If you are talking about UI (edit customer page) have a look at example below.

First, let's click "Add address" and pick "United states"
![address_state_us](https://user-images.githubusercontent.com/4091515/28358189-35ab8be8-6c6e-11e7-8970-36e272a64fc3.png)

Then, after changing country to "Poland" we can see that API has been called with `http://commerce.localhost/admin/api/rest/latest/country/regions/PL` and new States have been populated:
![address_state_pl](https://user-images.githubusercontent.com/4091515/28358243-77835168-6c6e-11e7-987c-a02c844ee7b5.png)

**Comment by sachingk** [comment] 2017-07-19 09:04
Hi There,

Below is the screenshot of what I am using :

[image: Inline image 2]

Before Country was set to India & State Gujarat was selected.
Not when I changed Country to Hong Kong, then State must get cleared. But
it's Still Gujarat is being shown.
[image: Inline image 1]

Regards,
Sachin G Kulkarni,
PHP Freelancer and Consultant,

Every business will get online
Only smart developer can nourish your online success.
I make websites in PHP and related technologies.
 http://sachingkulkarni.com/

*Skype : *sachin.g.kulkarni | *Mob:*  +91 9986057914

--------------------------------------------------------------------------------------------------------------------------------------------------
This message may contain confidential and/or proprietary information. It is
intended solely for the person/entity to whom it was originally addressed.
The content of this message may contain private views and opinions which do
not constitute a formal disclosure or commitment unless specifically
stated. If you are not the intended recipient, you should delete this
message and are hereby notified any disclosure, copying, printing,
retention or distribution of this message, or the taking of any action
based on it, is strictly prohibited.

On Wed, Jul 19, 2017 at 2:09 PM, Daniel Nahrebecki <notifications@github.com

**Comment by dnahrebecki** [comment] 2017-07-19 09:08
Please, edit your reply with proper screenshots, as they were not attached.

**Comment by aivus** [comment] 2017-07-19 09:11
Duplicate of https://github.com/orocrm/platform/issues/723

**Comment by sachingk** [comment] 2017-07-19 09:35
@dnahrebecki I have attached the link of screenshot

**Comment by dnahrebecki** [comment] 2017-07-19 09:57
@sachingk could you please open Developer Tools in browser / Network section and tell me what is the response of `/admin/api/rest/latest/country/regions/HK`? Are there any JS errors in console? Also, which version of application do you use?

**Comment by sachingk** [comment] 2017-07-19 12:31
There is no XRH request being triggered... I wonder why.. I observer where ever there is a address collection type being used I see this problem.

I don't see any issue when  there is a just a address type is used. 

By the by did you check with Customers Edit Screen ?

**Comment by manowark** [comment] 2017-07-24 15:54
Hi @sachingk .
I just try it on Customers Edit page. Issue not reproduced.
Which browser you use? Any errors in browser`s Development Tools console?

Also, version 1.1 not supported anymore. Please update your application to latest release and try to reproduce that issue on it.

**Comment by manowark** [comment] 2017-08-07 08:25
Hi, @sachingk. Do you have additional questions related to this issue?

**Comment by manowark** [comment] 2017-08-30 09:54
Issue closed as it has been inactive for a while. Please, feel free to reopen it if you have any questions.

**Closed by manowark** 2017-08-30 09:54 UTC
Labels: feedback needed, question
